const fs = require("fs");
const path = require("path");

const sourceFiles = [
  "providers/provider.js",
  "public/widget/pageReader.js",
  "public/widget/chatEngine.js",
  "public/widget/actionEngine.js",
  "public/widget/confirmUI.js",
  "public/widget/widget.js",
];

const distDir = path.join(__dirname, "dist");
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir);
}

function readSource(file) {
  const fullPath = path.join(__dirname, file);
  if (!fs.existsSync(fullPath)) {
    console.error(`Missing source file: ${file}`);
    process.exit(1);
  }
  return fs.readFileSync(fullPath, "utf-8");
}

let globalBundle = `/**
 * Widgetron - Embeddable AI website assistant
 * Classic global build - use via <script src="widgetron.js">.
 * For bundler-based projects (React/Vite/webpack), use widgetron.esm.js
 * (or just: import { init, createProvider } from "widgetron").
 * Do not edit this file directly - edit the source files and rebuild
 * with: node build.js
 */

`;

for (const file of sourceFiles) {
  globalBundle += `// ===== ${file} =====\n`;
  globalBundle += readSource(file);
  globalBundle += "\n\n";
}

fs.writeFileSync(path.join(distDir, "widgetron.js"), globalBundle);

function stripTrailingGuard(code) {
  return code
    .replace(/if \(typeof module !== "undefined"\)[\s\S]*$/, "")
    .replace(/if \(typeof window !== "undefined"\)[\s\S]*$/, "")
    .trimEnd();
}

let esmBundle = `/**
 * Widgetron - Embeddable AI website assistant
 * ES module build - use via: import { init, createProvider } from "widgetron";
 * Do not edit this file directly - edit the source files and rebuild
 * with: node build.js
 */

`;

for (const file of sourceFiles) {
  esmBundle += `// ===== ${file} =====\n`;
  esmBundle += stripTrailingGuard(readSource(file));
  esmBundle += "\n\n";
}

esmBundle += `export { createProvider, initWidget as init };\n`;

fs.writeFileSync(path.join(distDir, "widgetron.esm.js"), esmBundle);

const css = fs.readFileSync(
  path.join(__dirname, "public/widget/widget.css"),
  "utf-8",
);
fs.writeFileSync(path.join(distDir, "widgetron.css"), css);

console.log(
  "Built dist/widgetron.js, dist/widgetron.esm.js, and dist/widgetron.css",
);
