// Run this from the repo root with: node build.js
// Builds dist/widgetron.js and dist/widgetron.css from your actual source
// files. Load order matters — each file depends on functions defined in
// the ones before it, so don't change this order.

const fs = require("fs");
const path = require("path");

const sourceFiles = [
  "providers/provider.js",
  "public/widget/pageReader.js",
  "public/widget/chatEngine.js",
  "public/widget/actionEngine.js",
  "public/widget/confirmUI.js",
  "public/widget/widget.js",
];

const distDir = path.join(__dirname, "dist");
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir);
}

let bundle = `/**
 * Widgetron - Embeddable AI website assistant
 * Bundled build - do not edit this file directly, edit the source files
 * listed in build.js and rebuild with: node build.js
 */

`;

for (const file of sourceFiles) {
  const fullPath = path.join(__dirname, file);
  if (!fs.existsSync(fullPath)) {
    console.error(`Missing source file: ${file}`);
    process.exit(1);
  }
  bundle += `// ===== ${file} =====\n`;
  bundle += fs.readFileSync(fullPath, "utf-8");
  bundle += "\n\n";
}

fs.writeFileSync(path.join(distDir, "widgetron.js"), bundle);

const css = fs.readFileSync(
  path.join(__dirname, "public/widget/widget.css"),
  "utf-8",
);
fs.writeFileSync(path.join(distDir, "widgetron.css"), css);

console.log("Built dist/widgetron.js and dist/widgetron.css");
